name: deploy-cloud-run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up GCP
        uses: google-github-actions/setup-gcloud@v1

      - name: Build Image
        run: |
          gcloud builds submit \
          --tag asia-south1-docker.pkg.dev/prem-rasapalli-zomat/prem-repo/app:v1

      - name: Deploy
        run: |
          gcloud run deploy prem-rasapalli-zomat \
          --image asia-south1-docker.pkg.dev/prem-rasapalli-zomat/prem-repo/app:v1 \
          --region asia-south1 \
          --platform managed \
          --allow-unauthenticated
